repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-check
      #- id: ruff-format

  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
